apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PV_NAME}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: ${PV_NAME}
    volumeAttributes:
      resourceGroup: ${DATA_RESOURCE_GROUP}
      shareName: ${FILE_SHARE_NAME}
    nodeStageSecretRef:
      name: azure-secret
      namespace: ${AKS_NAMESPACE}
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
