apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PV_NAME}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: ${PV_NAME}
  resources:
    requests:
      storage: 5Gi
