apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: $AKS_NAMESPACE
type: Opaque
stringData:
  azurestorageaccountname: ${RAW_STORAGE_ACCT}
  azurestorageaccountkey: ${RAW_STORAGE_KEY}
