
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

on: [push, pull_request]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get git info
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Install Azure Infrastructure
      run: ./deploy/setup.sh pr${{ steps.vars.outputs.sha_short }} eastus custom-vision-model-v2 pr${{ steps.vars.outputs.sha_short }}-environment stellarbatchdev
      shell: bash

    - name: Grant Admin role for synapse workspace to github service-principal and TM-Stellar AAD group
      run: |
        # Granting role to principal-id used in github workflow
        az synapse role assignment create --workspace-name pr${{ steps.vars.outputs.sha_short }}-pipeline-syn-ws --role "Synapse Administrator" --assignee 8c0d8761-c477-4ab0-b1b1-eb25d7355294
        # Granting role to principal-id used in TM-Stellar AAD group
        az synapse role assignment create --workspace-name pr${{ steps.vars.outputs.sha_short }}-pipeline-syn-ws --role "Synapse Administrator" --assignee 68144578-3bde-4d74-b0dd-2a44972ea2f3
      shell: bash

    - name: Execute pipeline
      run: ./test/deploy-prepare-and-test-pipeline.sh pr${{ steps.vars.outputs.sha_short }}
      shell: bash

    - name: Cleanup the resources
      run: ./deploy/cleanup.sh pr${{ steps.vars.outputs.sha_short }} stellarbatchdev custom-vision-model-v2
      shell: bash